### ISSUE TITLE
No module named models

### ISSUE THREAD

**Issue by anishmahapatra01** [adar2378/bankingchatbotabc#2]
Traceback (most recent call last):
  File "bot-application/app.py", line 9, in <module>
    from models import *
ImportError: No module named models

There is no models.py file to be imported. The file that is generated after training has six files that are crf_model.pkl, entity_synonyms.json, intent_classifier_sklearn.pkl, metadata.json, regex_featurizer.json, training_data.json. Please help with this issue.

**Comment by adar2378** [comment]
That model is for a database. you can delete that line if you want.

**Comment by anishmahapatra** [comment]
Alright, thanks!
